
export const GET_MY_PLACES = "GET_MY_PLACES"
export const GET_MY_PLACES_RECEIVE = "GET_MY_PLACES_RECEIVE"
export const GET_MY_PLACES_ERROR = "GET_MY_PLACES_ERROR"

export const UPDATE_MY_PLACES = "UPDATE_MY_PLACES"
export const UPDATE_MY_PLACES_RECEIVE = "UPDATE_MY_PLACES_RECEIVE"
export const UPDATE_MY_PLACES_ERROR = "UPDATE_MY_PLACES_ERROR"

export const RESET_MY_FAVORITE_PLACE = "RESET_MY_FAVORITE_PLACE"
