export const CREATE_ACCOUNT = 'CREATE_ACCOUNT';
export const CREATE_ACCOUNT_RECEIVE = 'CREATE_ACCOUNT_RECEIVE';
export const CREATE_ACCOUNT_ERROR = 'CREATE_ACCOUNT_ERROR';

export const GET_USER_IP_ADDRESS = 'GET_USER_IP_ADDRESS';
export const GET_USER_IP_ADDRESS_RECEIVE = 'GET_USER_IP_ADDRESS_RECEIVE';
export const GET_USER_IP_ADDRESS_ERROR = 'GET_USER_IP_ADDRESS_ERROR';

export const GET_USER_GEOLOCATION = 'GET_USER_GEOLOCATION';
export const GET_USER_GEOLOCATION_RECEIVE = 'GET_USER_GEOLOCATION_RECEIVE';
export const GET_USER_GEOLOCATION_ERROR = 'GET_USER_GEOLOCATION_ERROR';

export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const GET_USER_PROFILE_RECEIVE = 'GET_USER_PROFILE_RECEIVE';
export const GET_USER_PROFILE_ERROR = 'GET_USER_PROFILE_ERROR';

export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_PROFILE_RECEIVE = 'UPDATE_PROFILE_RECEIVE';
export const UPDATE_PROFILE_ERROR = 'UPDATE_PROFILE_ERROR';

export const UPDATE_PROFILE_WITH_PHONE_NUMBER =
  'UPDATE_PROFILE_WITH_PHONE_NUMBER';
export const UPDATE_PROFILE_WITH_PHONE_NUMBER_RECEIVE =
  'UPDATE_PROFILE_WITH_PHONE_NUMBER_RECEIVE';
export const UPDATE_PROFILE_WITH_PHONE_NUMBER_ERROR =
  'UPDATE_PROFILE_WITH_PHONE_NUMBER_ERROR';

export const USER_STATE_PATH = 'USER_STATE_PATH ';
export const USER_STATE_PATH_RECEIVE = 'USER_STATE_PATH_RECEIVE ';

export const GET_USER_FULL_NAME = 'GET_USER_FULL_NAME';
export const GET_USER_FULL_NAME_RECEIVE = 'GET_USER_FULL_NAME_RECEIVE';
export const GET_USER_FULL_NAME_ERROR = 'GET_USER_FULL_NAME_ERROR';

export const CHECK_USER_NAME = 'CHECK_USER_NAME';
export const CHECK_USER_NAME_RECEIVE = 'CHECK_USER_NAME_RECEIVE';
export const CHECK_USER_NAME_ERROR = 'CHECK_USER_NAME_ERROR';

export const UPLOAD_AVATAR = 'UPLOAD_AVATAR';
export const UPLOAD_AVATAR_RECEIVE = 'UPLOAD_AVATAR_RECEIVE';
export const UPLOAD_AVATAR_ERROR = 'UPLOAD_AVATAR_ERROR';

export const USER_FEEDBACK = 'USER_FEEDBACK';
export const USER_FEEDBACK_RECEIVE = 'USER_FEEDBACK_RECEIVE';
export const USER_FEEDBACK_ERROR = 'USER_FEEDBACK_ERROR';

export const GET_USER_NAME = 'GET_USER_NAME';
export const USER_IS_LOGGED_OUT = 'USER_IS_LOGGED_OUT';
export const USER_IS_LOGGED_IN = 'USER_IS_LOGGED_IN';
export const GET_AVATAR = 'GET_AVATAR';
export const UPDATE_ERROR = 'UPDATE_ERROR';
