export const CREATE_FIREBASE_ACCOUNT = 'CREATE_FIREBASE_ACCOUNT';
export const CREATE_FIREBASE_ACCOUNT_RECEIVE =
  'CREATE_FIREBASE_ACCOUNT_RECEIVE';
export const CREATE_FIREBASE_ACCOUNT_ERROR = 'CREATE_FIREBASE_ACCOUNT_ERROR';

export const SIGNIN_TO_FIREBASE_ACCOUNT = 'SIGNIN_TO_FIREBASE_ACCOUNT';
export const SIGNIN_TO_FIREBASE_ACCOUNT_RECEIVE =
  'SIGNIN_TO_FIREBASE_ACCOUNT_RECEIVE';
export const SIGNIN_TO_FIREBASE_ACCOUNT_ERROR =
  'SIGNIN_TO_FIREBASE_ACCOUNT_ERROR';

export const SIGN_OUT_FIREBASE_ACCOUNT = 'SIGN_OUT_FIREBASE_ACCOUNT';
export const SIGN_OUT_FIREBASE_ACCOUNT_RECEIVE =
  'SIGN_OUT_FIREBASE_ACCOUNT_RECEIVE';
export const SIGN_OUT_FIREBASE_ACCOUNT_ERROR =
  'SIGN_OUT_FIREBASE_ACCOUNT_ERROR';

export const SIGNIN_WITH_PHONE_NUMBER = 'SIGNIN_WITH_PHONE_NUMBER';
export const SIGNIN_WITH_PHONE_NUMBER_RECEIVE =
  'SIGNIN_WITH_PHONE_NUMBER_RECEIVE';
export const SIGNIN_WITH_PHONE_NUMBER_ERROR = 'SIGNIN_WITH_PHONE_NUMBER_ERROR';

export const TOKEN_RECEIVE = 'TOKEN_RECEIVE';

export const SIGN_IN_FIREBASE = 'SIGN_IN_FIREBASE';

export const SEND_OTP = 'SEND_OTP';
export const SEND_OTP_RECEIVE = 'SEND_OTP_RECEIVE';
export const SEND_OTP_ERROR = 'SEND_OTP_ERROR';
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION';
