export const FETCH_INITIAL_DATA = 'FETCH_INITIAL_DATA';
export const FETCH_INITIAL_DATA_RECEIVE = 'FETCH_INITIAL_DATA';
export const FETCH_INITIAL_DATA_ERROR = 'FETCH_INITIAL_DATA';

export const FETCH_ALL_COUNTRIES = 'FETCH_ALL_COUNTRIES';
export const FETCH_ALL_COUNTRIES_RECEIVE = 'FETCH_ALL_COUNTRIES_RECEIVE';
export const FETCH_ALL_COUNTRIES_ERROR = 'FETCH_ALL_COUNTRIES_ERROR';
export const FETCH_ALL_GCC_COUNTRIES = 'FETCH_ALL_GCC_COUNTRIES';
export const FETCH_ALL_GCC_COUNTRIES_ERROR = 'FETCH_ALL_GCC_COUNTRIES_ERROR';
export const FETCH_ALL_GCC_COUNTRIES_RECEIVE =
  'FETCH_ALL_GCC_COUNTRIES_RECEIVE';

export const FETCH_ALL_CWHOTSPOTS = 'FETCH_ALL_CWHOTSPOTS';
export const FETCH_ALL_CWHOTSPOTS_RECEIVE = 'FETCH_ALL_CWHOTSPOTS_RECEIVE';
export const FETCH_ALL_CWHOTSPOTS_ERROR = 'FETCH_ALL_CWHOTSPOTS_ERROR';

export const FETCH_ALL_LANGUAGES = 'FETCH_ALL_LANGUAGES';
export const FETCH_ALL_LANGUAGES_RECEIVE = 'FETCH_ALL_LANGUAGES_RECEIVE';
export const FETCH_ALL_LANGUAGES_ERROR = 'FETCH_ALL_LANGUAGES_ERROR';

export const FETCH_ALL_QONGFUS = 'FETCH_ALL_QONGFUS';
export const FETCH_ALL_QONGFUS_RECEIVE = 'FETCH_ALL_QONGFUS_RECEIVE';
export const FETCH_ALL_QONGFUS_ERROR = 'FETCH_ALL_QONGFUS_ERROR';

export const GET_ALL_LIFESTYLES = 'GET_ALL_LIFESTYLES';
export const GET_ALL_LIFESTYLES_RECEIVE = 'GET_ALL_LIFESTYLES_RECEIVE';
export const GET_ALL_LIFESTYLES_ERROR = 'GET_ALL_LIFESTYLES_ERROR';

export const GET_ALL_SUB_LIFESTYLES = 'GET_ALL_SUB_LIFESTYLES';
export const GET_ALL_SUB_LIFESTYLES_RECEIVE = 'GET_ALL_SUB_LIFESTYLES_RECEIVE';
export const GET_ALL_SUB_LIFESTYLES_ERROR = 'GET_ALL_SUB_LIFESTYLES_ERROR';

export const FETCH_SEARCH_SUGGESTIONS = 'FETCH_SEARCH_SUGGESTIONS';
export const FETCH_SEARCH_SUGGESTIONS_RECEIVE =
  'FETCH_SEARCH_SUGGESTIONS_RECEIVE';
export const FETCH_SEARCH_SUGGESTIONS_ERROR = 'FETCH_SEARCH_SUGGESTIONS_ERROR';

export const GET_ALL_INTERESTS = 'GET_ALL_INTERESTS';
export const GET_ALL_INTERESTS_RECEIVE = 'GET_ALL_INTERESTS_RECEIVE';
export const GET_ALL_INTERESTS_ERROR = 'GET_ALL_INTERESTS_ERROR';

export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORIES_RECEIVE = 'GET_CATEGORIES_RECEIVE';
export const GET_SUB_CATEGORIES_RECEIVE = 'GET_SUB_CATEGORIES_RECEIVE';
export const GET_CATEGORIES_ERROR = 'GET_CATEGORIES_ERROR';

export const SEARCH_TAGS = 'SEARCH_TAGS';
export const SEARCH_TAGS_RECEIVE = 'SEARCH_TAGS_RECEIVE';
export const SEARCH_TAGS_ERROR = 'SEARCH_TAGS_ERROR';

export const GET_MARKETPLACE = 'GET_MARKETPLACE';
export const GET_MARKETPLACE_RECEIVE = 'GET_MARKETPLACE_RECEIVE';
export const GET_MARKETPLACE_ERROR = 'GET_MARKETPLACE_ERROR';

export const GET_MARKETPLACE_PROPERTIES = 'GET_MARKETPLACE_PROPERTIES';

export const LOAD_PAGE_MARKETPLACE = 'LOAD_PAGE_MARKETPLACE';
export const LOAD_PAGE_MARKETPLACE_PROPERTIES =
  'LOAD_PAGE_MARKETPLACE_PROPERTIES';
export const LOAD_PAGE_MARKETPLACE_RECEIVE = 'LOAD_PAGE_MARKETPLACE_RECEIVE';
export const LOAD_PAGE_MARKETPLACE_ERROR = 'LOAD_PAGE_MARKETPLACE_ERROR';

export const PLACE_PROFILE = 'PLACE_PROFILE';
export const PLACE_PROFILE_RECEIVE = 'PLACE_PROFILE_RECEIVE';
export const PLACE_PROFILE_ERROR = 'PLACE_PROFILE_ERROR';

export const SEARCH_SORT = 'SEARCH_SORT';
export const SET_SOCKET = 'SET_SOCKET';
